export const CALCULATE_MOVES = 'CALCULATE_MOVES'
export const SET_PLAYER1_NAME = 'SET_PLAYER1_NAME'
export const SET_PLAYER2_NAME = 'SET_PLAYER2_NAME'
export const INC_PLAYER_CAPTURED_PIECES = 'INC_PLAYER_CAPTURED_PIECES'